name: CI
on:
    push:
    
    workflow_dispatch:

jobs:

    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: build
              run: |
                chmod +x gradlew
                ./gradlew build
                ls -ltr
    
            - name: SonarCloud Analysis
              run: |
                chmod +x gradlew
                ./gradlew jacocoTestReport sonar -Dsonar.token=${{ secrets.SECRET_SONARCLOUD }} --info --stacktrace 

            - name: SonarQube Quality Gate check
              uses: sonarsource/sonarqube-quality-gate-action@master
              env:
               SONAR_TOKEN: ${{ secrets.SECRET_SONARCLOUD }} 
               SONAR_HOST_URL: https://sonarcloud.io
              with:
               scanMetadataReportFile: build/sonar/report-task.txt   

            - name: Print Jacoco Coverage Report
              run: cat build/reports/jacoco/test/jacocoTestReport.csv 

            - name: SonarCloud Analysis and JaCoCo Check
              run: |
                chmod +x gradlew
                ./gradlew check jacocoTestReport sonar -Dsonar.token=${{ secrets.SECRET_SONARCLOUD }} --info --stacktrace 

            - name: Docker Login
              uses: docker/login-action@v2.2.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Copy .jar file to root directory
              run: |
                cp $GITHUB_WORKSPACE/build/libs/*.jar .
                chmod 777 *.jar
                ls -lt

            - name: Docker Build
              run: |
                docker build --tag xamaztian/microservicio-java:latest .
                docker images

            - name: Docker Push
              run: |
                docker push xamaztian/microservicio-java:latest
                docker images
             
    deploy:
        runs-on: self-hosted
        needs: build
        steps:
            - uses: actions/checkout@v3
            - name: Deploy a Minikube local
              run: |
                kubectl apply -f deployment.yml
                POD_NAME=$(kubectl get pod -l app=microservicio-java-deployment -o jsonpath="{.items[0].metadata.name}")
                kubectl port-forward $POD_NAME 8080:8080

